repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v2.3.1"
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --follow-imports=silent

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
