name: Robot Framework CI

on:
  push:
    branches:
      - main
    # Do not run tests if file README.md changes
    paths-ignore:
      - '**.md'
  pull_request:
    # Do not run tests if file README.md changes
    paths-ignore:
      - '**.md'
  schedule:
    # Run tests nightly at 2am
    - cron:  '0 2 * * *'
jobs:
    Run-Test:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
        - name: Install dependencies
          run: uv sync --group dev
        - name: Run Robot tests
          run: ADDITIONAL_ROBOT_ARGS="--variable=additional_chrome_options:--headless" ./run-robot-tests
        - name: Publish test results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: robot-test-results
            path: tests/robot/output/
        - name: Generate Robot Framework test report
          if: always()
          uses: joonvena/robotframework-reporter-action@v2.5
          with:
            gh_access_token: ${{ secrets.GITHUB_TOKEN }}
            report_path: tests/robot/output
            show_passed_tests: true
            failed_tests_on_top: true
            only_summary: true
